# syntax=docker/dockerfile:1   # Specifies Dockerfile version to use. In this case, version 1.

# Defines the base image to use for your Docker image. Here, it is the slim-buster version of the official Python 3.9 img
FROM python:3.9-slim-buster

# Sets the working directory in the Docker container. Any command that follows in the Dockerfile will be run in this directory
WORKDIR /app

# Copies the requirements.txt and .env file from your project to the working directory in the Docker img
COPY requirements.txt .env* ./

# Runs pip install command in your Docker image to install Python dependencies listed in your requirements.txt file
RUN pip install -r requirements.txt

# Copies everything else in your project (denoted by '.') to the working directory in the Docker img
COPY . .
